from __future__ import annotations

from typing import Any, Protocol, TypeVar


class Scalar(Protocol):
    def __pos__(self: _S) -> _S: ...

    def __neg__(self: _S) -> _S: ...

    def __add__(self: _S, other: Any) -> _S: ...

    def __radd__(self: _S, other: Any) -> _S: ...

    def __sub__(self: _S, other: Any) -> _S: ...

    def __rsub__(self: _S, other: Any) -> _S: ...

    def __mul__(self: _S, other: Any) -> _S: ...

    def __rmul__(self: _S, other: Any) -> _S: ...

    def __truediv__(self: _S, other: Any) -> _S: ...

    def __rtruediv__(self: _S, other: Any) -> _S: ...

    def __lt__(self, other: Any) -> bool: ...


_T = TypeVar('_T')
_S = TypeVar('_S', bound=Scalar)
